apiVersion: "v1"
kind: "Service"
metadata:
  name: "filemanager-bot-lb-service"
spec:
  type: "LoadBalancer"
  # needs to be a premium IP
  loadBalancerIP: "35.246.157.192"
  selector:
    app: "filemanager-bot"
  ports:
  - protocol: "TCP"
    port: 1
    targetPort: 1337
