apiVersion: "v1"
kind: "Service"
metadata:
  name: "namespaces-lb-service"
spec:
  type: "LoadBalancer"
  # needs to be a premium IP
  loadBalancerIP: "35.246.140.24"
  selector:
    app: "namespaces"
  ports:
  - protocol: "TCP"
    port: 1
    targetPort: 1337
