apiVersion: "v1"
kind: "Service"
metadata:
  name: "krautflare-lb-service"
spec:
  type: "LoadBalancer"
  # needs to be a premium IP
  loadBalancerIP: "35.246.172.142"
  selector:
    app: "krautflare"
  ports:
  - protocol: "TCP"
    port: 1
    targetPort: 1337
